In [155]:
import numpy as np

NUM_SLOTS = 48  # 12 hours * 4 slots per hour

def hhmm_to_slot(hhmm: str) -> int:
    t = int(hhmm)
    h = t // 100
    m = t % 100
    slot = (h - 10) * 4 + (m // 15)
    return max(0, min(NUM_SLOTS - 1, slot))

def parse_availability(avail_str: str) -> list[int]:
    slots = [0] * NUM_SLOTS
    intervals = [s.strip() for s in avail_str.split(",")]
    for interval in intervals:
        if not interval:
            continue
        start, end = interval.split("-")
        s, e = hhmm_to_slot(start), hhmm_to_slot(end)
        slots[s] = 1
        slots[min(e,NUM_SLOTS)] = -1
    return slots

# Input availability strings
input_avail = [
    '1000-1200','2000-2200','1300-1430,2030-2200','1300-1430,2030-2200',
    '1300-1430,2030-2200,1000-1130','1000-1600','1000-1600','1030-1900',
    '1030-1900','1030-1900','1030-1900','1030-1900','1100-2200','1100-2200',
    '1100-2200','1200-2200','1200-2200','1145-1830','1145-2200','1200-2200',
    '1145-2200','1145-2200','1230-1400','1130-1300','1300-1430','1230-1630',
    '1600-1830','1600-1830','1400-1830','1400-1830','1000-1200','2000-2200',
    '1800-2030','1700-2200'
]

# Convert to matrix
schedule_matrix = np.array([parse_availability(av) for av in input_avail])

print(schedule_matrix.shape)  # (34, 48) -> 34 officers × 48 slots
np.set_printoptions(threshold=np.inf)

print(schedule_matrix)


(34, 48)
[[ 1  0  0  0  0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0 -1  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0 -1  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0 -1]
 [ 1  0  0  0  0  0 -1  0  0  0  0  0  1  0  0  0  0  0 -1  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0 -1]
 [ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  -1  0  0  0  0  0  0 

In [18]:
officer_in_out = schedule_matrix.sum(axis=0)
print(officer_in_out)
print(officer_in_out.shape)

[  5   0   5   0   3   0   0   4   1   0   2   0   3   0   0   0   1   0
  -4   0   0   0   0   0   0   0  -1   0   1   0   0   0   1   0  -5   0
  -5   0   0   0   2   0   2   0   0   0   0 -15]
(48,)


In [110]:
NUM_SLOTS = 48  # 12 hours * 4 slots per hour

def hhmm_to_slot(hhmm: str) -> int:
    t = int(hhmm)
    h = t // 100
    m = t % 100
    slot = (h - 10) * 4 + (m // 15)
    return max(0, min(NUM_SLOTS - 1, slot))

def parse_availability(avail_str: str) -> list[int]:
    slots = [-1] * NUM_SLOTS
    intervals = [s.strip() for s in avail_str.split(",")]
    for interval in intervals:
        if not interval:
            continue
        start, end = interval.split("-")
        s, e = hhmm_to_slot(start), hhmm_to_slot(end)
        for i in range(s, min(e, NUM_SLOTS)):
            slots[i] = 1
    return slots

def slots_to_intervals(slots: list[int]) -> list[tuple[int, int]]:
    intervals = []
    in_interval = False
    start = 0
    for i, v in enumerate(slots):
        if v == 1 and not in_interval:
            start = i
            in_interval = True
        elif v == -1 and in_interval:
            intervals.append((start, i - 1))
            in_interval = False
    if in_interval:
        intervals.append((start, NUM_SLOTS - 1))
    return intervals

# Input availability strings
input_avail = [
    '1000-1200','2000-2200','1300-1430,2030-2200','1300-1430,2030-2200',
    '1300-1430,2030-2200,1000-1130','1000-1600','1000-1600','1030-1900',
    '1030-1900','1030-1900','1030-1900','1030-1900','1100-2200','1100-2200',
    '1100-2200','1200-2200','1200-2200','1145-1830','1145-2200','1200-2200',
    '1145-2200','1145-2200','1230-1400','1130-1300','1300-1430','1230-1630',
    '1600-1830','1600-1830','1400-1830','1400-1830','1000-1200','2000-2200',
    '1800-2030','1700-2200'
]

def init_break_planner(input_avail):
    # Build dict {officer_id: [(start_slot,end_slot), ...]}
    officer_intervals = {
        officer_id + 1: slots_to_intervals(parse_availability(av))
        for officer_id, av in enumerate(input_avail)
    }

    schedule_matrix = np.array([parse_availability(av) for av in input_avail])

    print(officer_intervals)
    return officer_intervals, schedule_matrix


In [ ]:
from collections import defaultdict

# officer_intervals is from the previous step
inverted_dict = defaultdict(list)

for officer_id, intervals in officer_intervals.items():
    for interval in intervals:
        inverted_dict[interval].append(officer_id)

# Convert back to a normal dict if desired
inverted_dict = dict(inverted_dict)

print(inverted_dict)
# key is sos start, end 
# value is list of officer_id


{(0, 7): [1, 31], (40, 46): [2, 32], (12, 17): [3, 4, 5, 25], (42, 46): [3, 4, 5], (0, 5): [5], (0, 23): [6, 7], (2, 35): [8, 9, 10, 11, 12], (4, 46): [13, 14, 15], (8, 46): [16, 17, 20], (7, 33): [18], (7, 46): [19, 21, 22], (10, 15): [23], (6, 11): [24], (10, 25): [26], (24, 33): [27, 28], (16, 33): [29, 30], (32, 41): [33], (28, 46): [34]}


In [ ]:
next_open_counter = [40,30,20,10,39,29,19,9,38,28,18,8,37,27,17,7,36,26,16,6,35,25,15,5,
                     34,24,14,4,33,23,13,3,32,22,12,2,31,21,11,1]
num_officers = len(input_avail)  # change this to however many officers you have

officer_dict = {i: [] for i in range(1, num_officers + 1)}

print(officer_dict)

{1: [], 2: [], 3: [], 4: [], 5: [], 6: [], 7: [], 8: [], 9: [], 10: [], 11: [], 12: [], 13: [], 14: [], 15: [], 16: [], 17: [], 18: [], 19: [], 20: [], 21: [], 22: [], 23: [], 24: [], 25: [], 26: [], 27: [], 28: [], 29: [], 30: [], 31: [], 32: [], 33: [], 34: []}


t: 0
[ 0  4  5  6 30]
open new counter
t: 1
in equilibrium, no break now
t: 2
[ 7  8  9 10 11]
open new counter
t: 3
in equilibrium, no break now
t: 4
[12 13 14]
net in, 3 officers can go for break now
t: 5
in equilibrium, no break now
t: 6
[23]
[4]
in equilibrium, no break now
t: 7
[17 18 20 21]
net in, 4 officers can go for break now
t: 8
[15 16 19]
[ 0 30]
net in, 1 officers can go for break now
t: 9
in equilibrium, no break now
t: 10
[22 25]
net in, 2 officers can go for break now
t: 11
in equilibrium, no break now
t: 12
[ 2  3  4 24]
[23]
net in, 3 officers can go for break now
t: 13
in equilibrium, no break now
t: 14
in equilibrium, no break now
t: 15
in equilibrium, no break now
t: 16
[28 29]
[22]
net in, 1 officers can go for break now
t: 17
in equilibrium, no break now
t: 18
[ 2  3  4 24]
net out, 4 officers to come back from break now
t: 19
in equilibrium, no break now
t: 20
in equilibrium, no break now
t: 21
in equilibrium, no break now
t: 22
in equilibrium, no break now
t: 

In [103]:
def calculate_total_break(officer_intervals):
    officers_break_quota = {}
    for officer in officer_intervals:
        total_break = []
        for each_interval in officer_intervals[officer]:
            this_break = 0
            s,e = each_interval
            if e-s >= 36:
                total_break = [2,3,3]
                break
            elif e-s >= 20:
                this_break = 3
            elif e-s >= 10:
                this_break = 2
        if this_break > 0:
            total_break.append(this_break)
        officers_break_quota[officer] = total_break
    return officers_break_quota


officers_break_quota = calculate_total_break(officer_intervals)
print(officers_break_quota)

{1: [], 2: [], 3: [], 4: [], 5: [], 6: [3], 7: [3], 8: [3], 9: [3], 10: [3], 11: [3], 12: [3], 13: [2, 3, 3], 14: [2, 3, 3], 15: [2, 3, 3], 16: [2, 3, 3], 17: [2, 3, 3], 18: [3], 19: [2, 3, 3], 20: [2, 3, 3], 21: [2, 3, 3], 22: [2, 3, 3], 23: [], 24: [], 25: [], 26: [2], 27: [], 28: [], 29: [2], 30: [2], 31: [], 32: [], 33: [], 34: [2]}


In [ ]:

def check_break_eligibility(t, officers_break_quota, officer_intervals):
    #if 4 < t <= NUM_SLOTS-4 : 
    officers_upcoming_break = {k: v[0] for k, v in officers_break_quota.items() if v} # return officer id and length of upcoming break
    eligible_officers_break = { # no officers should go for break and at the start (1st h) and end (last h) of each sos period
    officer_id: length
    for officer_id, length in officers_upcoming_break.items()
    if any(start + 4 < t <= end-4-length for start, end in officer_intervals.get(officer_id, []))
    }
    return eligible_officers_break #return dict {officer_id:break_time}

for t in range(NUM_SLOTS):
    print('t',t)
    eligible_officers_break = check_break_eligibility(t, officers_break_quota,officer_intervals)
    print(eligible_officers_break)

eligible_officers_break = check_break_eligibility(t, officers_break_quota,officer_intervals)

t 0
{}
t 1
{}
t 2
{}
t 3
{}
t 4
{}
t 5
{6: 3, 7: 3}
t 6
{6: 3, 7: 3}
t 7
{6: 3, 7: 3, 8: 3, 9: 3, 10: 3, 11: 3, 12: 3}
t 8
{6: 3, 7: 3, 8: 3, 9: 3, 10: 3, 11: 3, 12: 3}
t 9
{6: 3, 7: 3, 8: 3, 9: 3, 10: 3, 11: 3, 12: 3, 13: 2, 14: 2, 15: 2}
t 10
{6: 3, 7: 3, 8: 3, 9: 3, 10: 3, 11: 3, 12: 3, 13: 2, 14: 2, 15: 2}
t 11
{6: 3, 7: 3, 8: 3, 9: 3, 10: 3, 11: 3, 12: 3, 13: 2, 14: 2, 15: 2}
t 12
{6: 3, 7: 3, 8: 3, 9: 3, 10: 3, 11: 3, 12: 3, 13: 2, 14: 2, 15: 2, 18: 3, 19: 2, 21: 2, 22: 2}
t 13
{6: 3, 7: 3, 8: 3, 9: 3, 10: 3, 11: 3, 12: 3, 13: 2, 14: 2, 15: 2, 16: 2, 17: 2, 18: 3, 19: 2, 20: 2, 21: 2, 22: 2}
t 14
{6: 3, 7: 3, 8: 3, 9: 3, 10: 3, 11: 3, 12: 3, 13: 2, 14: 2, 15: 2, 16: 2, 17: 2, 18: 3, 19: 2, 20: 2, 21: 2, 22: 2}
t 15
{6: 3, 7: 3, 8: 3, 9: 3, 10: 3, 11: 3, 12: 3, 13: 2, 14: 2, 15: 2, 16: 2, 17: 2, 18: 3, 19: 2, 20: 2, 21: 2, 22: 2, 26: 2}
t 16
{6: 3, 7: 3, 8: 3, 9: 3, 10: 3, 11: 3, 12: 3, 13: 2, 14: 2, 15: 2, 16: 2, 17: 2, 18: 3, 19: 2, 20: 2, 21: 2, 22: 2, 26: 2}
t 17
{8: 3, 9: 3, 

In [99]:
eligible_officers_break

{6: 3, 7: 3, 8: 3, 9: 3, 10: 3, 11: 3, 12: 3}

In [162]:
#break_schedule = {officer_id: [] for officer_id in officer_intervals}
def update_break_schedule(n_officers, eligible_officers_break, t, officers_break_quota, break_schedule): # n_officers represents officer count to reach equilibrium
    # Populate based on length
    officer_count = 0
    for officer_id in break_schedule:
        if officer_id in eligible_officers_break:
            length = eligible_officers_break[officer_id]
            break_schedule[officer_id].append([t + j for j in range(length)]) # add break schedule
            officers_break_quota[officer_id].pop(0) # update officer remaining break left
            officer_count += 1
            if officer_count == n_officers:
                return break_schedule, officers_break_quota
    return break_schedule, officers_break_quota



In [158]:
schedule_with_breaks = schedule_matrix.copy()

# Make the new matrix object type so we can store '#'
schedule_with_breaks = schedule_with_breaks.astype(object)


In [157]:
schedule_matrix


array([[ 1,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,
         0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,
         0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0, -1],
       [ 1,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  1,  0,  0,  0,
         0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 

In [170]:
schedule_with_breaks

array([[1, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, -1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, -1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, -1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, -1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, -1],
       [1, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, -1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, -1],
       [1, 0, 0, 0, 0, 0, 0, '#', '#', '#', '#', 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 

In [169]:
# Mark the breaks
for officer_id, break_slots in flat_dict.items():
    if break_slots:
        row_idx = officer_id - 1
        for col_idx in break_slots:
            schedule_with_breaks[row_idx, col_idx] = '#'  # mark break

In [163]:
officer_intervals, schedule_matrix = init_break_planner(input_avail)
officers_break_quota = calculate_total_break(officer_intervals)


def main_loop(schedule_matrix, officer_intervals, officers_break_quota):
    break_schedule = {officer_id: [] for officer_id in officer_intervals}
    for t in range(NUM_SLOTS):
        officer_in = np.where(schedule_matrix[:, t] == 1)[0]
        officer_out = np.where(schedule_matrix[:, t] == -1)[0]
        print('t:', t)
        if officer_in.size != 0:
            print(officer_in)
        if officer_out.size != 0:
            print(officer_out)
        n_officers = officer_in.size-officer_out.size
        if officer_in.size > officer_out.size:
            if t < 4: # too early to go for break, incoming officers will open new counters
                print ('open new counter')
            else:
                print ('net in,', officer_in.size-officer_out.size, 'officers can go for break now')
                eligible_officers_break = check_break_eligibility(t, officers_break_quota,officer_intervals)
                '______________'
                print(eligible_officers_break)
                print(n_officers)
                print ('eligible',eligible_officers_break)
                print (t)
                updated_break_schedule = update_break_schedule(n_officers, eligible_officers_break, t, officers_break_quota, break_schedule)
                
        elif officer_in.size == officer_out.size:
            print ('in equilibrium, no break now') #allocating any break now will disort the equilibrium
        else:
            if t == NUM_SLOTS-1:
                print('shift ended!')
            else:
                print ('net out,', officer_out.size-officer_in.size, 'officers to come back from break now') # to take over counters

    return updated_break_schedule

updated_break_schedule = main_loop(schedule_matrix, officer_intervals, officers_break_quota) 


{1: [(0, 7)], 2: [(40, 46)], 3: [(12, 17), (42, 46)], 4: [(12, 17), (42, 46)], 5: [(0, 5), (12, 17), (42, 46)], 6: [(0, 23)], 7: [(0, 23)], 8: [(2, 35)], 9: [(2, 35)], 10: [(2, 35)], 11: [(2, 35)], 12: [(2, 35)], 13: [(4, 46)], 14: [(4, 46)], 15: [(4, 46)], 16: [(8, 46)], 17: [(8, 46)], 18: [(7, 33)], 19: [(7, 46)], 20: [(8, 46)], 21: [(7, 46)], 22: [(7, 46)], 23: [(10, 15)], 24: [(6, 11)], 25: [(12, 17)], 26: [(10, 25)], 27: [(24, 33)], 28: [(24, 33)], 29: [(16, 33)], 30: [(16, 33)], 31: [(0, 7)], 32: [(40, 46)], 33: [(32, 41)], 34: [(28, 46)]}
t: 0
[ 0  4  5  6 30]
open new counter
t: 1
in equilibrium, no break now
t: 2
[ 7  8  9 10 11]
open new counter
t: 3
in equilibrium, no break now
t: 4
[12 13 14]
net in, 3 officers can go for break now
{}
3
eligible {}
4
t: 5
in equilibrium, no break now
t: 6
[23]
[4]
in equilibrium, no break now
t: 7
[17 18 20 21]
net in, 4 officers can go for break now
{6: 3, 7: 3, 8: 3, 9: 3, 10: 3, 11: 3, 12: 3}
4
eligible {6: 3, 7: 3, 8: 3, 9: 3, 10: 3, 11

In [167]:
flat_dict = {
    k: [item for sublist in v for item in sublist] if v else []
    for k, v in updated_break_schedule[0].items()}

In [168]:
flat_dict

{1: [],
 2: [],
 3: [],
 4: [],
 5: [],
 6: [7, 8, 9],
 7: [7, 8, 9],
 8: [7, 8, 9],
 9: [7, 8, 9],
 10: [8, 9, 10],
 11: [10, 11, 12],
 12: [10, 11, 12],
 13: [12, 13, 16, 17, 18, 28, 29, 30],
 14: [12, 13, 32, 33, 34],
 15: [12, 13],
 16: [40, 41],
 17: [40, 41],
 18: [],
 19: [],
 20: [],
 21: [],
 22: [],
 23: [],
 24: [],
 25: [],
 26: [],
 27: [],
 28: [],
 29: [],
 30: [],
 31: [],
 32: [],
 33: [],
 34: []}

In [165]:
print(updated_break_schedule[0])
updated_break_final = [item for sublist in updated_break_schedule[0] for item in sublist]

{1: [], 2: [], 3: [], 4: [], 5: [], 6: [[7, 8, 9]], 7: [[7, 8, 9]], 8: [[7, 8, 9]], 9: [[7, 8, 9]], 10: [[8, 9, 10]], 11: [[10, 11, 12]], 12: [[10, 11, 12]], 13: [[12, 13], [16, 17, 18], [28, 29, 30]], 14: [[12, 13], [32, 33, 34]], 15: [[12, 13]], 16: [[40, 41]], 17: [[40, 41]], 18: [], 19: [], 20: [], 21: [], 22: [], 23: [], 24: [], 25: [], 26: [], 27: [], 28: [], 29: [], 30: [], 31: [], 32: [], 33: [], 34: []}


TypeError: 'int' object is not iterable

In [9]:
# Sort by tuple naturally (first element, then second element)
sorted_inverted = dict(sorted(inverted_dict.items(), key=lambda x: (x[0][0], x[0][1])))

print(sorted_inverted)


{(0, 5): [5], (0, 7): [1, 31], (0, 23): [6, 7], (2, 35): [8, 9, 10, 11, 12], (4, 46): [13, 14, 15], (6, 11): [24], (7, 33): [18], (7, 46): [19, 21, 22], (8, 46): [16, 17, 20], (10, 15): [23], (10, 25): [26], (12, 17): [3, 4, 5, 25], (16, 33): [29, 30], (24, 33): [27, 28], (28, 46): [34], (32, 41): [33], (40, 46): [2, 32], (42, 46): [3, 4, 5]}


In [31]:
empty_counter = [1,2,3,4,5,6,7,8,9,10]

In [32]:
for sos_period in sorted_inverted:
    if sos_period[0] == 0:
        for s in sorted_inverted[sos_period]:
            start, end = sos_period
            schedule_matrix[s, start:end+1] = empty_counter[-1]

            schedule_matrix[s][0] = empty_counter[-1]
            empty_counter.pop()
            print(empty_counter)

            print(schedule_matrix)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[[-1 -1 -1 -1 -1 -1 -1 -1 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2
  -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2]
 [ 4 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2
  -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -1 -1 -1 -1 -1 -1 -1 -2]
 [-2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -1 -1 -1 -1 -1 -1 -2 -2 -2 -2 -2 -2
  -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -1 -1 -1 -1 -1 -2]
 [-2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -1 -1 -1 -1 -1 -1 -2 -2 -2 -2 -2 -2
  -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -1 -1 -1 -1 -1 -2]
 [-1 -1 -1 -1 -1 -1 -2 -2 -2 -2 -2 -2 -1 -1 -1 -1 -1 -1 -2 -2 -2 -2 -2 -2
  -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -1 -1 -1 -1 -1 -2]
 [10 10 10 10 10 10 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2]
 [ 2 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -2

In [27]:
import numpy as np

matrix = np.ones((3, 3), dtype=int)
print(matrix)
matrix[2,0] = 3
print(matrix)


[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [3 1 1]]
